version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: